version: '2'
services:

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD

  kamailio:
    build: ./kamailio
    environment:
      - MYSQL_ROOT_PASSWORD
      - SIP_DOMAIN
      - DBNAME
      - DBRWUSER
      - DBRWPW
      - DBROUSER
      - DBROPW
    ports:
      - "5060"
      - "5061/tcp"
      - "880/tcp"
      - "8443/tcp"

  rtpengine:
    build: ./rtpengine
    ports:
      - "30000-31000:30000-31000/udp"

  webphone:
    build: ./webphone
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN=$SIP_DOMAIN

  webpush-server:
    image: saycel/webpush-server
    environment:
      - PUSH_PUBLIC
      - PUSH_PRIVATE
      - PUSH_PORT
      - PUSH_SECRET
