version: '2'
services:

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD

  kamailio:
    build: ./kamailio
    environment:
      - MYSQL_ROOT_PASSWORD
      - DBNAME
      - DBRWUSER
      - DBRWPW
      - DBROUSER
      - DBROPW
      - SIP_DOMAIN=dev.webph.one
      - MY_DOMAIN=dev.webph.one
      - MY_WS_PORT=880
      - MY_WSS_PORT=8443
      - MY_PUSH_NOTIF_URL=http:\/\/127.0.0.1:3000
      - DBURL_REP=mysql:\/\/kamailio:kamailiorw@mysql\/kamailio
      - MY_RTPENGINE_IP_PORT=udp:rtpengine:2223
      - PRIVATE_KEY_PATH=\/certificates\/cert.key
      - CERTIFICATE_PATH=\/certificates\/cert.crt
      - DEBUG_LEVEL=2
    volumes:
      - ./certificates:/certificates
    ports:
      - "5060"
      - "5061/tcp"
      - "880/tcp"
      - "8443/tcp"
    links:
      - mysql
      - rtpengine
      - webpush-server

  rtpengine:
    build: ./rtpengine
    ports:
      - "2223"
      - "30000-31000:30000-31000/udp"

  webphone:
    build: ./webphone
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN=$SIP_DOMAIN
    volumes:
      - ./certificates:/certificates

  webpush-server:
    image: saycel/webpush-server
    environment:
      - PUSH_PUBLIC
      - PUSH_PRIVATE
      - PUSH_PORT
      - PUSH_SECRET
