version: '2'
services:

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD

  kamailio:
    build: ./kamailio
    environment:
      - MYSQL_ROOT_PASSWORD
      - DBNAME
      - DBRWUSER
      - DBRWPW
      - DBROUSER
      - DBROPW
      - SIP_DOMAIN
      - MY_DOMAIN
      - DOMAIN
      - MY_WS_PORT
      - MY_WSS_PORT
      - MY_PUSH_NOTIF_URL
      - DBURL_REP
      - MY_RTPENGINE_IP_PORT
      - PRIVATE_KEY_PATH
      - CERTIFICATE_PATH
      - DEBUG_LEVEL
    volumes:
      - ./certificates:/certificates
    ports:
      - "0.0.0.0:5060:5060"
      - "0.0.0.0:5061:5061/tcp"
      - "0.0.0.0:880:880/tcp"
      - "0.0.0.0:8443:8443/tcp"
    links:
      - mysql
      - rtpengine
      - webpush-server

  rtpengine:
    build: ./rtpengine
    ports:
      - "2223"
      - "30000-30010:30000-30010/udp"

  webphone:
    build: ./webphone
    environment:
      - MIN_PORT
      - MAX_PORT
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN
    volumes:
      - ./certificates:/certificates

  webpush-server:
    image: saycel/webpush-server
    environment:
      - PUSH_PUBLIC
      - PUSH_PRIVATE
      - PUSH_PORT
      - PUSH_SECRET
    ports:
      - "8080:3000"
    volumes:
      - ./certificates:/certificates
